######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 5 09:53:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=opengl
LIBS+=../../libandromeda.a
INCLUDEPATH+=../../include

# Input
HEADERS += SchematicWindow.h MainWindow.h QtSchematicRenderer.h
SOURCES += main.cpp SchematicWindow.cpp MainWindow.cpp QtSchematicRenderer.cpp
